name: TheSieuTocForm
version: '${project.version}'
main: me.khanh.thesieutocform.TheSieuTocFormPlugin
api-version: '1.13'
description: "Create top up form for Bedrock players based on Thesieutoc plugin"
depend:
  - Thesieutoc
commands:
  thesieutocformreload:
    description: Reload plugin TheSieuToc
    permission: thesieutocform.reload
